name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-26"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="your_prisma_accelerate_connection_pooling_string"

JWT_SECRET = "your_jwt_secret"